### findAll()

GET http://localhost:3000/api/characters/classes

###

POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
  "name": "Destruction",
  "descripcion": "Deals high amounts of AOE damage to enemies" 
}

### ID

### GET ONE

GET http://localhost:3000/api/characters/classes/1

### PUT

PUT http://localhost:3000/api/characters/classes/1
Content-Type: application/json

{
  "name": "Destruction",
  "descripcion": "Deals high amounts of AOE damage to enemies, but has a great single-target damage too" 
}

### POST para DELETE

POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
  "name": "Nihility",
  "descripcion": "Applies debuffs onto enemies" 
}

### DELETE

DELETE http://localhost:3000/api/characters/classes/2