### Obtenemos todos los characters

GET http://localhost:3000/api/characters

### Obtenemos un character

GET http://localhost:3000/api/characters/667e1e2d51752f0f7acc898a

### Crear un nuevo character

POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name": "Fu Xuan",
  "characterClass": "Preservation",
  "hp": 8000,
  "level": 70,
  "mana": 110,
  "items": ["Divination Widget", "Cosmic Insight"],
  "attack": 1300
}

### Modificar un character (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/characters/667e1e2d51752f0f7acc898a
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": "Self-Annihilator",
  "level": 80,
  "hp": 3400,
  "mana": 9,
  "attack": 3850,
  "items": ["Electric Sword", "Crimson Blossom"]
}

### Modificar un character (PATCH - recurso parcial)

PATCH http://localhost:3000/api/characters/667e1e2d51752f0f7acc898a
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": "Self-Annihilator",
  "level": 75,
  "items": ["Sharp Blade", "Remarkable Determination"]
}

### Borrar un character

DELETE http://localhost:3000/api/characters/667e1e2d51752f0f7acc898a