### Obtenemos todos los characters

GET http://localhost:3000/api/characters

### Obtenemos un character

GET http://localhost:3000/api/characters/1

### Crear un nuevo character

POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name": "Jingliu",
  "characterClass": 1,
  "level": 80,
  "hp": 2800,
  "mana": 130,
  "attack": 3030,
  "items": [3]
}

###

POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": 3,
  "level": 80,
  "hp": 3400,
  "mana": 9,
  "attack": 3850,
  "items": [4]
}

### Modificar un character (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/characters/3
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": 3,
  "level": 80,
  "hp": 3158,
  "mana": 9,
  "attack": 3150,
  "items": [4]
}

### Modificar un character (PATCH - recurso parcial)

PATCH http://localhost:3000/api/characters/3
Content-Type: application/json

{
  "level": 75
}

### Borrar un character

DELETE http://localhost:3000/api/characters/2