### Obtenemos todos los characters

GET http://localhost:3000/api/characters

### Obtenemos un character

GET http://localhost:3000/api/characters/2

### Crear un nuevo character

POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": "Nihility",
  "level": 80,
  "hp": 3157,
  "mana": 9,
  "attack": 3814,
  "items": ["Electric Sword", "Crimson Blossom"]
}

### Modificar un character (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/characters/3
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": "Self-Annihilator",
  "level": 80,
  "hp": 3400,
  "mana": 9,
  "attack": 3850,
  "items": ["Electric Sword", "Crimson Blossom"]
}

### Modificar un character (PATCH - recurso parcial)

PATCH http://localhost:3000/api/characters/3
Content-Type: application/json

{
  "name": "Acheron",
  "characterClass": "Self-Annihilator",
  "level": 75,
  "items": ["Sharp Blade", "Remarkable Determination"]
}

### Borrar un character

DELETE http://localhost:3000/api/characters/3