### GET ALL

GET http://localhost:3000/api/items

### POST

POST http://localhost:3000/api/items
Content-Type: application/json

{
  "name": "Blindfold",
  "descripcion": "Used by Jingliu for increased concentration to fight against mara"
}

### GET ONE
GET http://localhost:3000/api/items/1

### PUT

PUT http://localhost:3000/api/items/1
Content-Type: application/json

{
  "name": "Ice Sword",
  "descripcion": "Used by Jingliu to annihilate her enemies"
}

### POST PARA DELETE
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "name": "Electric Sword",
  "descripcion": "Used by Acheron to erase her enemies from existance itself"
}

### DELETE

DELETE http://localhost:3000/api/items/1